### ISSUE TITLE
fedmsg-relay --daemon ENVAL and flooding logs

### ISSUE THREAD

**Issue by glensc** [fedora-infra/fedmsg#302]
`fedmsg-relay` used with `--daemon`, appears not to be working (without `--daemon` option works fine) and floods `/var/log/fedmsg/fedmsg-relay.log` with: 

```
[2014-11-23 14:10:49][moksha.hub    INFO] Loading the Moksha Hub
[2014-11-23 14:10:49][moksha.hub    INFO] Binding publish socket to 'tcp://127.0.0.1:4001'
[2014-11-23 14:10:49][moksha.hub    INFO] Resolving 127.0.0.1 to ['127.0.0.1']
[2014-11-23 14:10:50][moksha.hub    INFO] Loading Consumers
[2014-11-23 14:10:50][    fedmsg    INFO]   enabled by config  - fedmsg.consumers.relay:RelayConsumer
[2014-11-23 14:10:50][moksha.hub   ERROR] Failed to init <class 'fedmsg.consumers.relay.RelayConsumer'> consumer.
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/moksha/hub/hub.py", line 363, in __init_consumers
  File "/usr/share/python2.7/site-packages/fedmsg/consumers/relay.py", line 36, in __init__
  File "/usr/share/python2.7/site-packages/fedmsg/consumers/__init__.py", line 98, in __init__
  File "/usr/share/python2.7/site-packages/moksha/hub/api/consumer.py", line 70, in __init__
  File "/usr/share/python2.7/site-packages/moksha/hub/hub.py", line 172, in subscribe
  File "/usr/share/python2.7/site-packages/moksha/hub/zeromq/zeromq.py", line 179, in subscribe
  File "/usr/share/python2.7/site-packages/txzmq/connection.py", line 173, in __init__
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 271, in addReader
    EPOLLIN, EPOLLOUT)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 257, in _add
    self._poller.register(fd, flags)
IOError: [Errno 22] Invalid argument
[2014-11-23 14:10:50][moksha.hub    INFO] Loading Producers
[2014-11-23 14:10:50][moksha.hub    INFO] Initializing MonitoringProducer producer
[2014-11-23 14:10:50][moksha.hub.monitoring    INFO] No 'moksha.monitoring.socket' defined.  Monitoring disabled.
[2014-11-23 14:10:50][moksha.hub    INFO] moksha.hub.monitoring:MonitoringProducer not initialized.
[2014-11-23 14:10:50][moksha.hub    INFO] Running the MokshaHub reactor
[2014-11-23 14:10:50][moksha.hub    INFO] Suggesting threadpool size at 1
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/fedmsg/commands/__init__.py", line 97, in _daemonize

  File "/usr/share/python2.7/site-packages/fedmsg/commands/relay.py", line 72, in run

  File "/usr/share/python2.7/site-packages/moksha/hub/__init__.py", line 109, in main

  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.doIteration(t)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 379, in doPoll
    l = self._poller.poll(timeout, len(self._selectables))
exceptions.IOError: [Errno 22] Invalid argument
Unhandled Error
```

more of that log: http://sprunge.us/iOgj

verified by `pingou`, so it's not from bad combination of libraries :)

```
13:29:57  pingou> http://fpaste.org/153456/28596141/
13:37:51  pingou> but running fedmsg-relay w/o daemon gives me a traceback though
13:38:06  pingou> (as root or as a normal user)
13:44:36  glen> look it's /var/log/
13:44:40  glen> it's flooding the errors there
13:57:42  pingou> 16G /var/log/fedmsg/fedmsg-relay.log
13:57:44  pingou> nice :)
```

**Comment by glensc** [comment]
ping

**Comment by glensc** [comment]
btw, `fedmsg-gateway` crashes the same way:

```
[2016-03-19 14:28:54][moksha.hub    INFO] Loading the Moksha Hub
[2016-03-19 14:28:54][moksha.hub WARNING] No 'zmq_publish_endpoints' set.  Are you sure?
[2016-03-19 14:28:55][moksha.hub    INFO] Loading Consumers
[2016-03-19 14:28:55][    fedmsg    INFO]   enabled by config  - fedmsg.consumers.gateway:GatewayConsumer
[2016-03-19 14:28:55][moksha.hub   ERROR] Failed to init <class 'fedmsg.consumers.gateway.GatewayConsumer'> consumer.
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/moksha/hub/hub.py", line 363, in __init_consumers
  File "/usr/share/python2.7/site-packages/fedmsg/consumers/gateway.py", line 36, in __init__
  File "/usr/share/python2.7/site-packages/fedmsg/consumers/__init__.py", line 98, in __init__
  File "/usr/share/python2.7/site-packages/moksha/hub/api/consumer.py", line 70, in __init__
  File "/usr/share/python2.7/site-packages/moksha/hub/hub.py", line 172, in subscribe
  File "/usr/share/python2.7/site-packages/moksha/hub/zeromq/zeromq.py", line 179, in subscribe
  File "/usr/share/python2.7/site-packages/txzmq/connection.py", line 173, in __init__
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 271, in addReader
    EPOLLIN, EPOLLOUT)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 257, in _add
    self._poller.register(fd, flags)
IOError: [Errno 22] Invalid argument
[2016-03-19 14:28:55][moksha.hub    INFO] Loading Producers
[2016-03-19 14:28:55][moksha.hub    INFO] Initializing MonitoringProducer producer
[2016-03-19 14:28:55][moksha.hub.monitoring    INFO] No 'moksha.monitoring.socket' defined.  Monitoring disabled.
[2016-03-19 14:28:55][moksha.hub    INFO] moksha.hub.monitoring:MonitoringProducer not initialized.
[2016-03-19 14:28:55][moksha.hub    INFO] Running the MokshaHub reactor
[2016-03-19 14:28:55][moksha.hub    INFO] Suggesting threadpool size at 1
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/fedmsg/commands/__init__.py", line 97, in _daemonize
    
  File "/usr/share/python2.7/site-packages/fedmsg/commands/gateway.py", line 67, in run
    
  File "/usr/share/python2.7/site-packages/moksha/hub/__init__.py", line 109, in main
    
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.doIteration(t)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 379, in doPoll
    l = self._poller.poll(timeout, len(self._selectables))
exceptions.IOError: [Errno 22] Invalid argument
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/fedmsg/commands/__init__.py", line 97, in _daemonize
    
  File "/usr/share/python2.7/site-packages/fedmsg/commands/gateway.py", line 67, in run
    
  File "/usr/share/python2.7/site-packages/moksha/hub/__init__.py", line 109, in main
    
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.doIteration(t)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 379, in doPoll
    l = self._poller.poll(timeout, len(self._selectables))
```

**Comment by glensc** [comment]
and `fedmsg-irc`:

```
[2016-03-19 14:31:08][moksha.hub    INFO] Loading the Moksha Hub
[2016-03-19 14:31:08][moksha.hub WARNING] No 'zmq_publish_endpoints' set.  Are you sure?
[2016-03-19 14:31:09][moksha.hub    INFO] Loading Consumers
[2016-03-19 14:31:09][    fedmsg    INFO]   enabled by config  - fedmsg.consumers.ircbot:IRCBotConsumer
[2016-03-19 14:31:09][moksha.hub   ERROR] Failed to init <class 'fedmsg.consumers.ircbot.IRCBotConsumer'> consumer.
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/moksha/hub/hub.py", line 363, in __init_consumers
  File "/usr/share/python2.7/site-packages/fedmsg/consumers/ircbot.py", line 191, in __init__
  File "/usr/share/python2.7/site-packages/fedmsg/consumers/__init__.py", line 98, in __init__
  File "/usr/share/python2.7/site-packages/moksha/hub/api/consumer.py", line 70, in __init__
  File "/usr/share/python2.7/site-packages/moksha/hub/hub.py", line 172, in subscribe
  File "/usr/share/python2.7/site-packages/moksha/hub/zeromq/zeromq.py", line 179, in subscribe
  File "/usr/share/python2.7/site-packages/txzmq/connection.py", line 173, in __init__
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 271, in addReader
    EPOLLIN, EPOLLOUT)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 257, in _add
    self._poller.register(fd, flags)
IOError: [Errno 22] Invalid argument
[2016-03-19 14:31:09][moksha.hub    INFO] Loading Producers
[2016-03-19 14:31:09][moksha.hub    INFO] Initializing MonitoringProducer producer
[2016-03-19 14:31:09][moksha.hub.monitoring    INFO] No 'moksha.monitoring.socket' defined.  Monitoring disabled.
[2016-03-19 14:31:09][moksha.hub    INFO] moksha.hub.monitoring:MonitoringProducer not initialized.
[2016-03-19 14:31:09][moksha.hub    INFO] Running the MokshaHub reactor
[2016-03-19 14:31:09][moksha.hub    INFO] Suggesting threadpool size at 1
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/fedmsg/commands/__init__.py", line 97, in _daemonize
    
  File "/usr/share/python2.7/site-packages/fedmsg/commands/ircbot.py", line 62, in run
    
  File "/usr/share/python2.7/site-packages/moksha/hub/__init__.py", line 109, in main
    
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.doIteration(t)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 379, in doPoll
    l = self._poller.poll(timeout, len(self._selectables))
exceptions.IOError: [Errno 22] Invalid argument
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/fedmsg/commands/__init__.py", line 97, in _daemonize
    
  File "/usr/share/python2.7/site-packages/fedmsg/commands/ircbot.py", line 62, in run
    
  File "/usr/share/python2.7/site-packages/moksha/hub/__init__.py", line 109, in main
    
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.doIteration(t)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 379, in doPoll
    l = self._poller.poll(timeout, len(self._selectables))
```

**Comment by glensc** [comment]
ping! can this be dealt finally?

**Comment by jeremycline** [comment]
Hey, sorry this ticket didn't get attended to for over a year 😞 

#470  actually ripped this functionality out - I recommend running these services via systemd or some other init system. If that's not possibly, please let me know what problems there are with that approach and we'll see if we can come up with a solution.
