### ISSUE TITLE
python sample does not work like suggested in docs

### ISSUE THREAD

**Issue by glensc** [fedora-infra/fedmsg#304]
Python sample from http://fedmsg.readthedocs.org/en/latest/#publishing-messages-with-python
does not seem to work without extra configuration:

```
$ python test.py 
/usr/share/python2.7/site-packages/fedmsg/core.py:153: UserWarning: fedmsg is not configured to send any messages for name '__main__.rotten-fruit'
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    'test': "Hello World",
  File "/usr/share/python2.7/site-packages/fedmsg/__init__.py", line 71, in _wrapper
  File "/usr/share/python2.7/site-packages/fedmsg/__init__.py", line 86, in publish
  File "/usr/share/python2.7/site-packages/fedmsg/core.py", line 296, in publish
AttributeError: 'FedMsgContext' object has no attribute 'publisher'

$ cat test.py 
import fedmsg

fedmsg.publish(topic='testing', modname='test', msg={
    'test': "Hello World",
})
$ hostname
rotten-fruit
```

the solution is to fill `/etc/fedmsg.d/endpoints.py`, which is not mentioned in that doc

```
21:07:23  threebean> you need a '__main__.rotten-fruit' entry in /etc/fedmsg.d/endpoints.py
21:15:46  threebean> glen: something like this -> http://fpaste.org/155568/14174613/
```

``` python
config = dict(
    # This is a dict of possible addresses from which fedmsg can send
    # messages.  fedmsg.init(...) requires that a 'name' argument be passed
    # to it which corresponds with one of the keys in this dict.
    endpoints={
        "__main__.rotten-fruit": [
            "tcp://127.0.0.1:4321",
        ]
    },
)
```

and it still does not print output to fedmsg-tail, will be updating this ticket when i get more information.

**Comment by Velmont** [comment]
I was really bitten in the ass about this too.  Maybe it would be good to mention something about this not really working?

**Comment by frenzymadness** [comment]
IMHO this issue can be closed.

**Comment by glensc** [comment]
if the fix is changing some timeout, then it's not resolved imho.

```
21:40:20 glen> post_init_sleep=0.5,
21:40:24 glen> is in default base.py
21:40:52 glen> changing to 1 seems better indeed
```
