### ISSUE TITLE
fedmsg-tail crashes if M2Crypto isn't installed

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/fedmsg#346]
I'm trying to do some quick dumb fedmsg openQA integration testing, so I just installed fedmsg from source, which didn't install M2Crypto because it's supposedly 'optional' - it seems like things should work but with no crypto.

However, it looks like `fedmsg-tail` crashes when run without it:

    adamw@openqa:~/fedmsg> fedmsg-tail --really-pretty
    WARNING:fedmsg.crypto.x509:Crypto disabled ImportError('No module named M2Crypto',)
    [2015-08-13 12:37:39][fedmsg.crypto.x509 WARNING] Failed validation.  M2Crypto and/or m2ext missing!
    Traceback (most recent call last):
      File "/usr/bin/fedmsg-tail", line 9, in <module>
        load_entry_point('fedmsg==0.14.1', 'console_scripts', 'fedmsg-tail')()
      File "/usr/lib/python2.7/site-packages/fedmsg-0.14.1-py2.7.egg/fedmsg/commands/tail.py", line 196, in tail
        return command.execute()
      File "/usr/lib/python2.7/site-packages/fedmsg-0.14.1-py2.7.egg/fedmsg/commands/__init__.py", line 104, in execute
        return self.run()
      File "/usr/lib/python2.7/site-packages/fedmsg-0.14.1-py2.7.egg/fedmsg/commands/tail.py", line 172, in run
        for name, ep, topic, message in fedmsg.tail_messages(**self.config):
      File "/usr/lib/python2.7/site-packages/fedmsg-0.14.1-py2.7.egg/fedmsg/__init__.py", line 109, in tail_messages
        for item in __local.__context.tail_messages(**kw):
      File "/usr/lib/python2.7/site-packages/fedmsg-0.14.1-py2.7.egg/fedmsg/core.py", line 374, in tail_messages
        if not validate or fedmsg.crypto.validate(msg, **self.c):
      File "/usr/lib/python2.7/site-packages/fedmsg-0.14.1-py2.7.egg/fedmsg/crypto/__init__.py", line 256, in validate
        return backend.validate(message, **cfg)
      File "/usr/lib/python2.7/site-packages/fedmsg-0.14.1-py2.7.egg/fedmsg/crypto/x509.py", line 125, in validate
        cert = M2Crypto.X509.load_cert_string(certificate)
    NameError: global name 'M2Crypto' is not defined

Maybe I missed something obvious, but...

**Comment by AdamWill** [comment]
OK, so it's "optional" in the sense that it works if you disable message validation.
