### ISSUE TITLE
fedmsg-hub installed from pypi crashes with `ValueError: No config value 'endpoints' found.`

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fedmsg#399]
If you install fedmsg-hub from pypi, and you don't have any `fedmsg*` rpm packages installed in the system (therefore there's no `/etc/fedmsg.d/`), `fedmsg-hub` crashes on launch:

```
$ fedmsg-hub 
Traceback (most recent call last):
  File "/home/kparal/devel/taskotron/taskotron-trigger/env_trigger/bin/fedmsg-hub", line 11, in <module>
    load_entry_point('fedmsg==0.18.2', 'console_scripts', 'fedmsg-hub')()
  File "/home/kparal/devel/taskotron/taskotron-trigger/env_trigger/lib/python2.7/site-packages/fedmsg/commands/hub.py", line 122, in hub
    command = HubCommand()
  File "/home/kparal/devel/taskotron/taskotron-trigger/env_trigger/lib/python2.7/site-packages/fedmsg/commands/__init__.py", line 53, in __init__
    self.config = self.get_config()
  File "/home/kparal/devel/taskotron/taskotron-trigger/env_trigger/lib/python2.7/site-packages/fedmsg/commands/__init__.py", line 61, in get_config
    fedmsg_command=True,
  File "/home/kparal/devel/taskotron/taskotron-trigger/env_trigger/lib/python2.7/site-packages/fedmsg/config.py", line 162, in load_config
    raise ValueError("No config value 'endpoints' found.")
ValueError: No config value 'endpoints' found.
```

That seems to be an error, there should be some defaults that allow the hub to run even without a configuration file. Alternatively, there should be an explanatory message describing what the user needs to do in order to have the hub working, and not just a cryptic traceback.

Reproducer:
```
$ rpm -qa | grep fedmsg
$ # nothing
$ ls /etc/fedmsg.d
ls: cannot access '/etc/fedmsg.d': No such file or directory
$ virtualenv --system-site-packages env
$ source env/bin/activate
$ pip install 'fedmsg[consumers]'
$ fedmsg-hub
```

**Comment by ktdreyer** [comment]
I hit a similar error when running in a virtualenv where I simply wanted to call the `fedpkg.meta.*` methods to parse messages coming from [another STOMP module](https://nikipore.github.io/stompest/async.html).

Here is a reproducer, using the code copied exactly from [the fedmsg docs](http://www.fedmsg.com/en/stable/_modules/fedmsg/meta/#make_processors):

```python
>>> import fedmsg.config
>>> import fedmsg.meta
>>> config = fedmsg.config.load_config([], None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/fedmsg/venv/lib/python2.7/site-packages/fedmsg-1.0.1-py2.7.egg/fedmsg/config.py", line 159, in load_config
    raise ValueError("No config value 'endpoints' found.")
ValueError: No config value 'endpoints' found.
```

My workaround was to call `load_config()` with a really small file that defines the expected endpoints dict.
```python
config = fedmsg.config.load_config(filenames=['fedmsgconfig.py'])
```
```
$ cat fedmsgconfig.py 
config = {'endpoints': {}}
```

Looks like there's a couple other tickets around the config API issues. It would be nice to make "endpoints" optional somehow. It looks like `load_config()` is deprecated entirely in master, so maybe this is better now?
