### ISSUE TITLE
pip lacks pygments dep?

### ISSUE THREAD

**Issue by glensc** [fedora-infra/fedmsg#504]
```
$ pip2 install fedmsg
Collecting fedmsg
  Downloading fedmsg-1.1.0-py2.py3-none-any.whl (487kB)
    100% |████████████████████████████████| 491kB 472kB/s
Collecting six (from fedmsg)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting requests (from fedmsg)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting arrow (from fedmsg)
  Downloading arrow-0.12.1.tar.gz (65kB)
    100% |████████████████████████████████| 71kB 1.3MB/s
Collecting kitchen (from fedmsg)
  Downloading kitchen-1.2.5.tar.gz (255kB)
    100% |████████████████████████████████| 256kB 1.3MB/s
Collecting pyzmq (from fedmsg)
  Downloading pyzmq-16.0.4-cp27-cp27m-macosx_10_6_intel.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 745kB/s
Collecting idna<2.7,>=2.5 (from requests->fedmsg)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->fedmsg)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->fedmsg)
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
    100% |████████████████████████████████| 153kB 1.7MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests->fedmsg)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting python-dateutil (from arrow->fedmsg)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting backports.functools_lru_cache>=1.2.1 (from arrow->fedmsg)
  Downloading backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Building wheels for collected packages: arrow, kitchen
  Running setup.py bdist_wheel for arrow ... done
  Stored in directory: /Users/glen/Library/Caches/pip/wheels/8b/f0/11/a675889f0f47d50ace5f8e1015c138c10a90e50327078710fd
  Running setup.py bdist_wheel for kitchen ... done
  Stored in directory: /Users/glen/Library/Caches/pip/wheels/4d/17/3c/820b146a84636dfe99c1844aa3e567ede2a0797a370c8aa20e
Successfully built arrow kitchen
Installing collected packages: six, idna, urllib3, certifi, chardet, requests, python-dateutil, backports.functools-lru-cache, arrow, kitchen, pyzmq, fedmsg
Successfully installed arrow-0.12.1 backports.functools-lru-cache-1.5 certifi-2018.1.18 chardet-3.0.4 fedmsg-1.1.0 idna-2.6 kitchen-1.2.5 python-dateutil-2.6.1 pyzmq-16.0.4 requests-2.18.4 six-1.11.0 urllib3-1.22

$ fedmsg-tail --pretty
Traceback (most recent call last):
  File "/usr/local/bin/fedmsg-tail", line 7, in <module>
    from fedmsg.commands.tail import tail
  File "/usr/local/lib/python2.7/site-packages/fedmsg/commands/tail.py", line 24, in <module>
    import pygments
ImportError: No module named pygments
```

**Comment by jeremycline** [comment]
fedmsg has extra requirements, but the code doesn't do conditional imports or anything. Doing ``pip install fedmsg[commands]`` pulls in pygments.

A fix for this would be to add some guards to anywhere using pygments.

**Comment by glensc** [comment]
indeed. i should read installation doc, not just assume `pip install fedmsg` does the thing
